monitor:
  pm2_5_min: 20
  pm2_5_max: 200
  pm10_min: 40
  pm10_max: 400
  float_precision: 2
  send_interval: 30000

mqtt:
  broker:
    host: 172.17.0.2
    port: 1883
  topics:
    pm2_5: /air/1/pm2.5
    pm10: /air/1/pm10

# log values but don't publish if true
dryrun: false   
